import { GoogleSpreadsheet } from "google-spreadsheet";
import { JWT } from "google-auth-library";

import * as dotenv from "dotenv";
import { SPREADSHEET_ID } from "./constants";
dotenv.config();

// Initialize auth - see https://theoephraim.github.io/node-google-spreadsheet/#/guides/authentication
const serviceAccountAuth = new JWT({
  // env var values here are copied from service account credentials generated by google
  // see "Authentication" section in docs for more info
  email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,
  key: process.env.GOOGLE_PRIVATE_KEY,
  scopes: ["https://www.googleapis.com/auth/spreadsheets"],
});

export const spreadsheet = new GoogleSpreadsheet(
  SPREADSHEET_ID,
  serviceAccountAuth
);
