import { GoogleSpreadsheet } from "google-spreadsheet";
import { JWT } from "google-auth-library";
import { ethers } from "ethers";

import { SPREADSHEET_ID } from "./constants";
import * as dotenv from "dotenv";
import { HypercertClient } from "@hypercerts-org/sdk";
dotenv.config();

// Initialize auth - see https://theoephraim.github.io/node-google-spreadsheet/#/guides/authentication
const serviceAccountAuth = new JWT({
  // env var values here are copied from service account credentials generated by google
  // see "Authentication" section in docs for more info
  email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,
  key: process.env.GOOGLE_PRIVATE_KEY,
  scopes: ["https://www.googleapis.com/auth/spreadsheets"],
});

export const spreadsheet = new GoogleSpreadsheet(
  SPREADSHEET_ID,
  serviceAccountAuth
);

// NOTE: you should replace this with your own JSON-RPC provider to the network
// This should have signing abilities and match the `chainId` passed into HypercertClient
const provider = new ethers.providers.AlchemyProvider(
  "goerli",
  process.env.ALCHEMY_API
);

const privateKey = process.env.PRIVATE_KEY;
let operator: ethers.providers.Provider | ethers.Signer;
if (privateKey) {
  operator = new ethers.Wallet(privateKey, provider);
} else {
  operator = provider;
}

// export const client = new HypercertClient({
//   chainId: 5,
//   operator,
//   nftStorageToken: process.env.NFT_STORAGE_API,
//   web3StorageToken: process.env.WEB3_STORAGE_API,
// });

export const getClient = () =>
  import("@hypercerts-org/sdk").then(
    ({ HypercertClient }) =>
      new HypercertClient({
        chainId: 5,
        operator,
        nftStorageToken: process.env.NFT_STORAGE_API,
        web3StorageToken: process.env.WEB3_STORAGE_API,
      })
  );
